#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: open5gs
#  namespace: argocd
#spec:
#  project: digital-twins-0
#  source:
#    repoURL: 'https://github.com/5gplustactile/deployment-digital-twins.git'
#    targetRevision: main
#    path: telefonica
#    helm:
#      valueFiles:
#        - values.yaml
#  destination:
#    server: 'https://internal-c0-apiserver-332551658.eu-west-3.elb.amazonaws.com:6443'
#    namespace: open5gs
#  syncPolicy:
#    automated: {}
#    syncOptions:
#      - CreateNamespace=true
#      - ApplyOutOfSyncOnly=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: digital-twins-0
  source:
    repoURL: 'https://github.com/5gplustactile/deployment-digital-twins.git'
    targetRevision: main
    path: digital-twins-0/demo/whoami/overlays
    kustomize:
      namePrefix: whoami
  destination:
    server: 'https://internal-c0-apiserver-332551658.eu-west-3.elb.amazonaws.com:6443'
    namespace: whoami
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
